// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMure9zF59le6XvWdRx0akQnl1TEfAitc',
    appId: '1:63766514477:web:62360ba83c367e82ec21a4',
    messagingSenderId: '63766514477',
    projectId: 'alphaeci',
    authDomain: 'alphaeci.firebaseapp.com',
    storageBucket: 'alphaeci.firebasestorage.app',
    measurementId: 'G-85V6B72DT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJdnjAatWtFgE376x7m_ELUkXmHA0kvu0',
    // App Android registrada como com.alphaeci.app (no la com.example).
    appId: '1:63766514477:android:5bd6ae9c4f3895caec21a4',
    messagingSenderId: '63766514477',
    projectId: 'alphaeci',
    storageBucket: 'alphaeci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-SsBUYiH4GJCgH5vJfxsveTXKfy-kio',
    appId: '1:63766514477:ios:24fa5a19acf1e400ec21a4',
    messagingSenderId: '63766514477',
    projectId: 'alphaeci',
    storageBucket: 'alphaeci.firebasestorage.app',
    iosBundleId: 'com.example.alphafront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw-SsBUYiH4GJCgH5vJfxsveTXKfy-kio',
    appId: '1:63766514477:ios:24fa5a19acf1e400ec21a4',
    messagingSenderId: '63766514477',
    projectId: 'alphaeci',
    storageBucket: 'alphaeci.firebasestorage.app',
    iosBundleId: 'com.example.alphafront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMure9zF59le6XvWdRx0akQnl1TEfAitc',
    appId: '1:63766514477:web:c4f302b1682401eeec21a4',
    messagingSenderId: '63766514477',
    projectId: 'alphaeci',
    authDomain: 'alphaeci.firebaseapp.com',
    storageBucket: 'alphaeci.firebasestorage.app',
    measurementId: 'G-SVED4R7MSN',
  );
}
